name: CustomTags
version: 1.0
main: com.flyerzrule.mc.customtags.CustomTags
api-version: 1.18
description: A plugin that allows players to select their custom tags
commands:
  tags:
    description: Show you all of the tags you own.
    usage: /<command>
  addtag:
    description: Show you all of the tags you own
    usage: /<command> [username] [tagId]