name: CustomTags
version: ${version}
main: com.flyerzrule.mc.customtags.CustomTags
author: flyerzrule
api-version: 1.18
description: A plugin that allows players to select their custom tags
depend: [Vault, Essentials, LuckPerms, KillionCommons, SimpleClans]
commands:
  tags:
    description: Show you all of the tags you own
    usage: /<command>
    permission: customtags.view
    permission-message: You do not have permission to use this command.
  taguser:
    description: Show the specified user's owned tags
    usage: /<command> [username]
    permission: customtags.manage
    permission-message: You do not have permission to use this command.
  tagadd:
    description: Add a tag to a player's account
    usage: /<command> [username] [tagId]
    permission: customtags.manage
    permission-message: You do not have permission to use this command.
  tagaddall:
    description: Add all tags to a player's account
    usage: /<command> [username]
    permission: customtags.manage
    permission-message: You do not have permission to use this command.
  tagremove:
    description: Remove a tag from a player's account
    usage: /<command> [username] [tagId]
    permission: customtags.manage
    permission-message: You do not have permission to use this command.
  tagremoveall:
    description: Remove all tags from a player's account
    usage: /<command> [username]
    permission: customtags.manage
    permission-message: You do not have permission to use this command.
  tagcreate:
    description: Create a new tag
    usage: /<command> [tagId] [tag] [material] [obtainable] "[name]" "[description]"
    permission: customtags.manage
    permission-message: You do not have permission to use this command.
  tagdelete:
    description: Delete a tag
    usage: /<command> [tagId]
    permission: customtags.manage
    permission-message: You do not have permission to use this command.
  tagmodify:
    description: Modify a tag
    usage: /<command> [tagId] [tag] [material] [obtainable] "[name]" "[description]"
    permission: customtags.manage
    permission-message: You do not have permission to use this command.
permissions:
  customtags.view:
    description: Allows the player to view and set their tag
    default: true
  customtags.manage:
    description: Allows the player to add and remove tags from people. As well as set the tag for a user
    default: op
