name: CustomTags
version: 1.0
main: com.flyerzrule.mc.customtags.CustomTags
api-version: 1.18
description: A plugin that allows players to select their custom tags
depend: [Vault, Essentials]
commands:
  tags:
    description: Show you all of the tags you own.
    usage: /<command>
  addtag:
    description: Add a tag to a player's account
    usage: /<command> [username] [tagId]
  removetag:
    description: remove a tag fom a player's account
    usage: /<command> [username] [tagId]