name: Build and Upload Release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Build with Gradle
        uses: KillionRevival/gradle-builder-action@v1
        id: build-step
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.PAT }}

      - name: Upload Release Asset
        id: release
        uses: KillionRevival/release-action@v1
        with:
          jar-path: ${{ steps.build.outputs.jar-path }}

      - name: Deploy to package repo
        id: deploy
        uses: KillionRevival/gradle-deploy-action@v1
        
