name: Build and Upload Release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: bash gradlew assemble
        shell: bash
        env:
          GITHUB_ACTOR: ${{ github.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      # - name: Upload Release Asset
      #   id: release
      #   uses: KillionRevival/release-action@v1
      #   with:
      #     jar-path: ${{ steps.build.outputs.jar-path }}

      # - name: Deploy to package repo
      #   id: deploy
      #   uses: KillionRevival/gradle-deploy-action@v1
        
