name: Build and Upload Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        id: build
        uses: actions/maven-builder-action@v1

      - name: Upload Release Asset
        id: release
        uses: actions/maven-release-action@v1
        with:
          jar-path: ${{ steps.build.outputs.jar-path }}
        
